# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - practisecicd

on:
  push:
    branches:
      - master
    paths: # Restrict workflow to changes in the backend folder
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Matches your original Node.js version

      - name: npm install, build, and test
        working-directory: backend # Run commands inside the backend folder
        run: |
          npm install
          npm run build --if-present # Use --if-present if you might not have a build script

      - name: Zip artifact for deployment
        run: |
          cd backend # Change into the backend directory
          zip -r ../release.zip ./* # Zip its contents, save to parent directory
        # The 'release.zip' will now be at the root of the workflow's workspace

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip # Path to the zipped artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production' # GitHub Environment for deployment
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for OpenID Connect (OIDC) authentication
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8DA6ECAD102E4CC4962392B01DBCDA13 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DF020F19F1A54D609A6DC833B75DDCDC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_552B246D46734AB3A7FA105807B99637 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'practisecicd' # Matches your Azure App Service name
          slot-name: 'Production' # Default slot
          package: . # The unzipped contents are in the current directory
